[package]
name = "deckard-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
deckard = { path = "../deckard" }
clap = { version = "4", features = ["derive", "cargo"] }
log = "0.4"
env_logger = "0.11"
crossterm = { version = "0.28", features = ["event-stream"] }
ratatui = "0.29"
color-eyre = "0.6"
trash = "5.2"
open = "5.3"
humansize = "2.1"
tokio = { version = "1.44", features = ["full"] }
futures = "0.3"
