[package]
name = "deckard-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive", "cargo"] }
colored = "3.0"
log = "0.4"
env_logger = "0.11"
color-eyre = "0.6"
deckard = {path = "../deckard"}
